name: main

on:
    push:
        branches: ["main"]

jobs:
    lint-and-build:
        uses: ./.github/workflows/ci.yml
        secrets: inherit

    publish:
        needs: lint-and-build
        uses: ./.github/workflows/publish.yml
        secrets: inherit
