name: Publish to NPM

on: workflow_call

jobs:
    lint-and-build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4
            - uses: oven-sh/setup-bun@v2

            - uses: actions/cache@v3
              with:
                  path: node_modules
                  key: node-modules-cache-${{ hashFiles('./bun.lockb') }}

            - name: Installing dependencies
              run: bun install

            - name: Building...
              run: bun run build

            - name: Setting NPM API key
              run: npm config set -- '//registry.npmjs.org/:_authToken' "${{ secrets.NPM_TOKEN }}"

            - name: Publishing to npm
              run: npm publish --access public
